const PROJECT_MEMBER_ROLES = ['ADMIN', 'MEMBER']
const PROJECT_STATUSES = ['PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED']
const TASK_PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'URGENT']
const TASK_STATUSES = ['TODO', 'IN_PROGRESS', 'REVIEW', 'DONE']
const USER_ROLES = ['admin', 'member']

export {
  PROJECT_MEMBER_ROLES,
  PROJECT_STATUSES,
  TASK_PRIORITIES,
  TASK_STATUSES,
  USER_ROLES,
}
